package au.gov.australia.itsecurity.core.pwd.generator;

public enum ValidationErrorType {
	REUSED_CREDENTIALS,
	SEQUENTIAL_CHARACTERS,
	REPEATED_CHARACTERS,
	REPEATED_SUBSTRINGS,
	ILLEGAL_WHITESPACE,
	INSUFFICIENT_CHARACTERS,
	LOWERCASE_MISSING,
	UPPERCASE_MISSING,
	DIGIT_MISSING,
	NONALPHANUMERIC_MISSING,
	BIRTHDATE_CHARACTERS,
	YEAR_1900_TO_2000,
	UNDEFINED;
}